# Generated by Django 5.1.2 on 2026-08-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_cou_subject_a09399_idx',
            old_name='courses_cou_subject_5d0e17_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_cou_is_publ_fd1efe_idx',
            old_name='courses_cou_is_publ_2c1a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_subject_2c95d0_idx',
            old_name='courses_les_subject_a2b3d8_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_kind_a7c593_idx',
            old_name='courses_les_kind_e91b45_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='courses_les_topic_p_d175ba_idx',
            old_name='courses_les_topic_p_74af62_idx',
        ),
        migrations.RenameIndex(
            model_name='lessoncompletion',
            new_name='courses_les_user_id_277c42_idx',
            old_name='courses_les_user_id_c8d491_idx',
        ),
    ]
