# Generated by Django 5.1.2 on 2026-04-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_question_types_difficulty_matching'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='attestation_test_id_fc1226_idx',
            old_name='attestation_test_id_diff_idx',
        ),
    ]
