# Generated by Django 5.1.2 on 2026-05-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0005_topic_pool_and_mock_tests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='attestation_pool_id_12cac1_idx',
            old_name='attestation_pool_diff_idx',
        ),
        migrations.RenameIndex(
            model_name='test',
            new_name='attestation_pool_id_81e62e_idx',
            old_name='attestation_test_pool_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='topicpool',
            new_name='attestation_subject_06c74c_idx',
            old_name='attestation_pool_subject_idx',
        ),
    ]
