# Generated by Django 5.1.2 on 2026-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0008_test_multi_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pools',
            field=models.ManyToManyField(related_name='tests', through='attestation.TestPool', to='attestation.topicpool'),
        ),
    ]
