# Generated by Django 5.1.2 on 2026-05-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0010_question_objection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionobjection',
            new_name='attestation_status_3e6d5c_idx',
            old_name='objection_status_idx',
        ),
        migrations.RenameIndex(
            model_name='questionobjection',
            new_name='attestation_user_id_3c93b0_idx',
            old_name='objection_user_idx',
        ),
    ]
