# Generated by Django 5.1.2 on 2026-04-28 10:08

import apps.presentations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='presentations/covers/')),
                ('slide_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='personalization.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentations', to='personalization.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PresentationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='presentations.presentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=apps.presentations.models.slide_upload_path)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['subject', 'grade'], name='presentatio_subject_62bfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['is_published', '-created_at'], name='presentatio_is_publ_89d3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationview',
            index=models.Index(fields=['user', '-viewed_at'], name='presentatio_user_id_281009_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationview',
            index=models.Index(fields=['presentation', '-viewed_at'], name='presentatio_present_8f8df0_idx'),
        ),
        migrations.AddConstraint(
            model_name='slide',
            constraint=models.UniqueConstraint(fields=('presentation', 'order'), name='slide_order_unique'),
        ),
    ]
