# Generated by Django 5.1.2 on 2026-07-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_presentation_pptx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
