# Generated by Django 5.1.2 on 2026-08-11 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalization', '0001_initial'),
        ('presentations', '0003_presentation_quarter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=200)),
                ('num_slides', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('processing', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=12)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PresentationPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_presentations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='presentation',
            index=models.Index(fields=['author', '-created_at'], name='presentatio_author__a5d248_idx'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='personalization.grade'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_job', to='presentations.presentation'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='personalization.subject'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentationpurchase',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presentationpurchase',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='presentations.presentation'),
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['user', '-created_at'], name='presentatio_user_id_80358a_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationpurchase',
            index=models.Index(fields=['buyer', '-created_at'], name='presentatio_buyer_i_816de2_idx'),
        ),
        migrations.AddConstraint(
            model_name='presentationpurchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'presentation'), name='unique_presentation_purchase'),
        ),
    ]
